<a href="https://colab.research.google.com/github/santolina/pytorch_handbook/blob/master/PyTorchHandbook_chap2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# isntall torch
!pip install torch
!pip install torchvision

In [0]:
import torch
import numpy as np

In [3]:
torch.__version__

'1.3.1'

# Section 2.2 Tensor

In [4]:
# Sec 2.2 Tensor

torch_array = torch.tensor([0, 1, 2, 3])
torch_array

tensor([0, 1, 2, 3])

In [6]:
np_array = np.array([0, 1, 2, 3])
np_array

array([0, 1, 2, 3])

In [7]:
# convert np_array to torch_array
torch_array = torch.from_numpy(np_array)
torch_array

tensor([0, 1, 2, 3])

In [8]:
type(torch_array)

torch.Tensor

In [9]:
# tensor to np.array, example of 1D array
torch2np_array = torch_array.numpy()
torch2np_array

array([0, 1, 2, 3])

In [10]:
type(torch2np_array)

numpy.ndarray

In [12]:
# tensor to np.array, example of 2D array
np_array = np.array(np.arange(16).reshape([4,4]))
torch_array = torch.from_numpy(np_array)
torch2np_array = torch_array.numpy()
torch_array

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [13]:
# tensor to np.array, example of 3D array
np_array = np.array(np.arange(27).reshape([3,3,3]))
torch_array = torch.from_numpy(np_array)
torch2np_array = torch_array.numpy()
torch2np_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [14]:
# torch.arange
torch_array = torch.arange(10)
torch_array

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a = torch.arange(10)
b = torch.arange(10)/2
c = a+b
c, a, b

(tensor([ 0,  1,  3,  4,  6,  7,  9, 10, 12, 13]),
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([0, 0, 1, 1, 2, 2, 3, 3, 4, 4]))

In [18]:
c = a*b
c

tensor([ 0,  0,  2,  3,  8, 10, 18, 21, 32, 36])

In [21]:
c = a@b
c

tensor(130)

In [23]:
# torch.linspace
torch_array = torch.linspace(0, 1, 6)
torch_array

tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000, 1.0000])

In [25]:
# torch.ones
torch_array = torch.ones([3,3])
torch_array

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [27]:
# torch.zeros
torch_array = torch.zeros([4,4])
torch_array

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# torch.randn
torch_array = torch.randn(4)
torch_array 

tensor([-0.6602,  2.0652, -0.6862, -0.1971])

In [29]:
# Reshape
torch_array = torch.arange(10)
print(torch_array)
torch_array = torch_array.view(5,2)
print(torch_array)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [30]:
# swap axis
torch_array = torch.arange(10)
torch_array = torch_array.view(5,2)
print(torch_array)
torch_array = torch_array.transpose(0,1)
print(torch_array)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([[0, 2, 4, 6, 8],
        [1, 3, 5, 7, 9]])


In [35]:
torch_array = torch.arange(27).view(3,3,3)
print(torch_array)
torch_array = torch_array.transpose(1,2)
print(torch_array)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])
tensor([[[ 0,  3,  6],
         [ 1,  4,  7],
         [ 2,  5,  8]],

        [[ 9, 12, 15],
         [10, 13, 16],
         [11, 14, 17]],

        [[18, 21, 24],
         [19, 22, 25],
         [20, 23, 26]]])


In [36]:
torch_array = torch.arange(27).view(3,3,3)
print(torch_array)
torch_array = torch_array.transpose(0,2)
print(torch_array)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])
tensor([[[ 0,  9, 18],
         [ 3, 12, 21],
         [ 6, 15, 24]],

        [[ 1, 10, 19],
         [ 4, 13, 22],
         [ 7, 16, 25]],

        [[ 2, 11, 20],
         [ 5, 14, 23],
         [ 8, 17, 26]]])


In [37]:
torch_array = torch.arange(27).view(3,3,3)
print(torch_array)
torch_array = torch_array.transpose(0,1)
print(torch_array)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])
tensor([[[ 0,  1,  2],
         [ 9, 10, 11],
         [18, 19, 20]],

        [[ 3,  4,  5],
         [12, 13, 14],
         [21, 22, 23]],

        [[ 6,  7,  8],
         [15, 16, 17],
         [24, 25, 26]]])


In [38]:
# specify by index
torch_array = torch.arange(10)
torch_array[2]

tensor(2)

In [40]:
# slice
torch_array[2:7]

tensor([2, 3, 4, 5, 6])

In [42]:
# element-wise addition
x1 = torch.arange(4)
print(x1)
print(torch.add(x1, 4))

# element-wise multiplication
x1 = torch.arange(4)
print(torch.mul(x1, 4))

tensor([0, 1, 2, 3])
tensor([4, 5, 6, 7])
tensor([ 0,  4,  8, 12])


In [43]:
# various calculation
# inner product
x1 = torch.arange(4)
x2 = torch.arange(4)
print(torch.matmul(x1,x2))
print(torch.dot(x1,x2))
print(x1@x2)

tensor(14)
tensor(14)
tensor(14)


In [45]:
# product by mat and vector
X1 = torch.arange(8).view(2,4)
x2 = torch.arange(4)
print(torch.matmul(X1, x2))
print(torch.mv(X1, x2))


tensor([14, 38])
tensor([14, 38])


In [47]:
# product by mat and mat
X1 = torch.arange(8).view(2,4)
X2 = torch.arange(8).view(2,4).t()
print(torch.matmul(X1,X2))
print(torch.mm(X1,X2))
print(X1@X2)

tensor([[ 14,  38],
        [ 38, 126]])
tensor([[ 14,  38],
        [ 38, 126]])
tensor([[ 14,  38],
        [ 38, 126]])


In [48]:
# various calculation 2
# matmul by mat with shape=(2,4) and mat with shape=(4,2)
X1 = torch.arange(24).view(-1, 2, 4)
X2 = torch.arange(24).view(-1, 4, 2)
print(X1.size())
print(X2.size())
print(torch.matmul(X1, X2))
print(torch.bmm(X1,X2))
print(X1@X2)

torch.Size([3, 2, 4])
torch.Size([3, 4, 2])
tensor([[[  28,   34],
         [  76,   98]],

        [[ 428,  466],
         [ 604,  658]],

        [[1340, 1410],
         [1644, 1730]]])
tensor([[[  28,   34],
         [  76,   98]],

        [[ 428,  466],
         [ 604,  658]],

        [[1340, 1410],
         [1644, 1730]]])
tensor([[[  28,   34],
         [  76,   98]],

        [[ 428,  466],
         [ 604,  658]],

        [[1340, 1410],
         [1644, 1730]]])


In [49]:
# data type
np_array = np.array([1,2,3])
np_array.dtype

dtype('int64')

In [50]:
np_array = np.array([1.,2.,3.])
np_array.dtype

dtype('float64')

In [51]:
np_array = np.array([0,1,2,3])
torch_array = torch.from_numpy(np_array)
torch_array.type()

'torch.LongTensor'

In [52]:
torch_array.dtype

torch.int64

In [53]:
np_array = np.array([0.,1.,2.,3.])
torch_array = torch.from_numpy(np_array)
torch_array.type()

'torch.DoubleTensor'

In [54]:
torch_array.dtype

torch.float64

In [55]:
np_array = np.array([1,2,3], dtype=float)
np_array.dtype

dtype('float64')

In [56]:
np_array = np.array([1,2,3]).astype(np.float)
torch_array = torch.from_numpy(np_array)
torch_array.dtype

torch.float64

In [57]:
np_array = np.array([1,2,3], dtype="int64")
torch_array = torch.from_numpy(np_array)
torch_array.dtype

torch.int64

In [58]:
torch_array.type()

'torch.LongTensor'

In [59]:
# shape check
xf_numpy = np.ndarray([2,3], dtype='float32')
print(xf_numpy)
print(xf_numpy.shape)

[[0.    1.875 0.   ]
 [2.    0.    2.125]]
(2, 3)


In [60]:
xf_torch = torch.FloatTensor(2,3)
print(xf_torch)
print(xf_torch.shape)

tensor([[3.9781e-37, 0.0000e+00, 3.7835e-44],
        [0.0000e+00,        nan, 6.1657e-44]])
torch.Size([2, 3])


# Section 2.3 Network Definition
