<a href="https://colab.research.google.com/github/santolina/pytorch_handbook/blob/master/PyTorchHandbook_chap2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# isntall torch
!pip install torch
!pip install torchvision

In [0]:
import torch
import numpy as np

In [3]:
torch.__version__

'1.3.1'

# Section 2.2 Tensor

In [4]:
# Sec 2.2 Tensor

torch_array = torch.tensor([0, 1, 2, 3])
torch_array

tensor([0, 1, 2, 3])

In [5]:
np_array = np.array([0, 1, 2, 3])
np_array

array([0, 1, 2, 3])

In [6]:
# convert np_array to torch_array
torch_array = torch.from_numpy(np_array)
torch_array

tensor([0, 1, 2, 3])

In [7]:
type(torch_array)

torch.Tensor

In [8]:
# tensor to np.array, example of 1D array
torch2np_array = torch_array.numpy()
torch2np_array

array([0, 1, 2, 3])

In [9]:
type(torch2np_array)

numpy.ndarray

In [10]:
# tensor to np.array, example of 2D array
np_array = np.array(np.arange(16).reshape([4,4]))
torch_array = torch.from_numpy(np_array)
torch2np_array = torch_array.numpy()
torch_array

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [11]:
# tensor to np.array, example of 3D array
np_array = np.array(np.arange(27).reshape([3,3,3]))
torch_array = torch.from_numpy(np_array)
torch2np_array = torch_array.numpy()
torch2np_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [12]:
# torch.arange
torch_array = torch.arange(10)
torch_array

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a = torch.arange(10)
b = torch.arange(10)/2
c = a+b
c, a, b

(tensor([ 0,  1,  3,  4,  6,  7,  9, 10, 12, 13]),
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([0, 0, 1, 1, 2, 2, 3, 3, 4, 4]))

In [14]:
c = a*b
c

tensor([ 0,  0,  2,  3,  8, 10, 18, 21, 32, 36])

In [15]:
c = a@b
c

tensor(130)

In [16]:
# torch.linspace
torch_array = torch.linspace(0, 1, 6)
torch_array

tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000, 1.0000])

In [17]:
# torch.ones
torch_array = torch.ones([3,3])
torch_array

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [18]:
# torch.zeros
torch_array = torch.zeros([4,4])
torch_array

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# torch.randn
torch_array = torch.randn(4)
torch_array 

tensor([-0.9942,  1.9328,  0.9196, -0.5386])

In [20]:
# Reshape
torch_array = torch.arange(10)
print(torch_array)
torch_array = torch_array.view(5,2)
print(torch_array)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [21]:
# swap axis
torch_array = torch.arange(10)
torch_array = torch_array.view(5,2)
print(torch_array)
torch_array = torch_array.transpose(0,1)
print(torch_array)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([[0, 2, 4, 6, 8],
        [1, 3, 5, 7, 9]])


In [22]:
torch_array = torch.arange(27).view(3,3,3)
print(torch_array)
torch_array = torch_array.transpose(1,2)
print(torch_array)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])
tensor([[[ 0,  3,  6],
         [ 1,  4,  7],
         [ 2,  5,  8]],

        [[ 9, 12, 15],
         [10, 13, 16],
         [11, 14, 17]],

        [[18, 21, 24],
         [19, 22, 25],
         [20, 23, 26]]])


In [23]:
torch_array = torch.arange(27).view(3,3,3)
print(torch_array)
torch_array = torch_array.transpose(0,2)
print(torch_array)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])
tensor([[[ 0,  9, 18],
         [ 3, 12, 21],
         [ 6, 15, 24]],

        [[ 1, 10, 19],
         [ 4, 13, 22],
         [ 7, 16, 25]],

        [[ 2, 11, 20],
         [ 5, 14, 23],
         [ 8, 17, 26]]])


In [24]:
torch_array = torch.arange(27).view(3,3,3)
print(torch_array)
torch_array = torch_array.transpose(0,1)
print(torch_array)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])
tensor([[[ 0,  1,  2],
         [ 9, 10, 11],
         [18, 19, 20]],

        [[ 3,  4,  5],
         [12, 13, 14],
         [21, 22, 23]],

        [[ 6,  7,  8],
         [15, 16, 17],
         [24, 25, 26]]])


In [25]:
# specify by index
torch_array = torch.arange(10)
torch_array[2]

tensor(2)

In [26]:
# slice
torch_array[2:7]

tensor([2, 3, 4, 5, 6])

In [27]:
# element-wise addition
x1 = torch.arange(4)
print(x1)
print(torch.add(x1, 4))

# element-wise multiplication
x1 = torch.arange(4)
print(torch.mul(x1, 4))

tensor([0, 1, 2, 3])
tensor([4, 5, 6, 7])
tensor([ 0,  4,  8, 12])


In [28]:
# various calculation
# inner product
x1 = torch.arange(4)
x2 = torch.arange(4)
print(torch.matmul(x1,x2))
print(torch.dot(x1,x2))
print(x1@x2)

tensor(14)
tensor(14)
tensor(14)


In [29]:
# product by mat and vector
X1 = torch.arange(8).view(2,4)
x2 = torch.arange(4)
print(torch.matmul(X1, x2))
print(torch.mv(X1, x2))


tensor([14, 38])
tensor([14, 38])


In [30]:
# product by mat and mat
X1 = torch.arange(8).view(2,4)
X2 = torch.arange(8).view(2,4).t()
print(torch.matmul(X1,X2))
print(torch.mm(X1,X2))
print(X1@X2)

tensor([[ 14,  38],
        [ 38, 126]])
tensor([[ 14,  38],
        [ 38, 126]])
tensor([[ 14,  38],
        [ 38, 126]])


In [31]:
# various calculation 2
# matmul by mat with shape=(2,4) and mat with shape=(4,2)
X1 = torch.arange(24).view(-1, 2, 4)
X2 = torch.arange(24).view(-1, 4, 2)
print(X1.size())
print(X2.size())
print(torch.matmul(X1, X2))
print(torch.bmm(X1,X2))
print(X1@X2)

torch.Size([3, 2, 4])
torch.Size([3, 4, 2])
tensor([[[  28,   34],
         [  76,   98]],

        [[ 428,  466],
         [ 604,  658]],

        [[1340, 1410],
         [1644, 1730]]])
tensor([[[  28,   34],
         [  76,   98]],

        [[ 428,  466],
         [ 604,  658]],

        [[1340, 1410],
         [1644, 1730]]])
tensor([[[  28,   34],
         [  76,   98]],

        [[ 428,  466],
         [ 604,  658]],

        [[1340, 1410],
         [1644, 1730]]])


In [32]:
# data type
np_array = np.array([1,2,3])
np_array.dtype

dtype('int64')

In [33]:
np_array = np.array([1.,2.,3.])
np_array.dtype

dtype('float64')

In [34]:
np_array = np.array([0,1,2,3])
torch_array = torch.from_numpy(np_array)
torch_array.type()

'torch.LongTensor'

In [35]:
torch_array.dtype

torch.int64

In [36]:
np_array = np.array([0.,1.,2.,3.])
torch_array = torch.from_numpy(np_array)
torch_array.type()

'torch.DoubleTensor'

In [37]:
torch_array.dtype

torch.float64

In [38]:
np_array = np.array([1,2,3], dtype=float)
np_array.dtype

dtype('float64')

In [39]:
np_array = np.array([1,2,3]).astype(np.float)
torch_array = torch.from_numpy(np_array)
torch_array.dtype

torch.float64

In [40]:
np_array = np.array([1,2,3], dtype="int64")
torch_array = torch.from_numpy(np_array)
torch_array.dtype

torch.int64

In [41]:
torch_array.type()

'torch.LongTensor'

In [42]:
# shape check
xf_numpy = np.ndarray([2,3], dtype='float32')
print(xf_numpy)
print(xf_numpy.shape)

[[0.    1.875 0.   ]
 [2.    0.    2.125]]
(2, 3)


In [43]:
xf_torch = torch.FloatTensor(2,3)
print(xf_torch)
print(xf_torch.shape)

tensor([[1.2214e-37, 0.0000e+00, 3.7835e-44],
        [0.0000e+00,        nan, 0.0000e+00]])
torch.Size([2, 3])


# Section 2.3 Network Definition


In [44]:
#1 network define using sequential manner

import torch.nn as nn

model = nn.Sequential(
    nn.Conv2d(1, 20, 5),
    nn.ReLU(),
    nn.Conv2d(20, 60, 5),
    nn.ReLU()
)

model

Sequential(
  (0): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU()
  (2): Conv2d(20, 60, kernel_size=(5, 5), stride=(1, 1))
  (3): ReLU()
)

In [45]:
#2 network define using add module
model = torch.nn.Sequential()

model.add_module('conv1', nn.Conv2d(1,20,5))
model.add_module('relu1', nn.ReLU())
model.add_module('conv2', nn.Conv2d(20,64,5))
model.add_module('relu2', nn.ReLU())

model

Sequential(
  (conv1): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
  (relu1): ReLU()
  (conv2): Conv2d(20, 64, kernel_size=(5, 5), stride=(1, 1))
  (relu2): ReLU()
)

In [46]:
#3 network define using OrderedDict
from collections import OrderedDict

layersDict = OrderedDict([
                          ('conv1', nn.Conv2d(1, 20, 5)),
                          ('relu1', nn.ReLU()),
                          ('conv2', nn.Conv2d(20, 60, 5)),
                          ('relu2', nn.ReLU())])

model = nn.Sequential(layersDict)
model


Sequential(
  (conv1): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
  (relu1): ReLU()
  (conv2): Conv2d(20, 60, kernel_size=(5, 5), stride=(1, 1))
  (relu2): ReLU()
)

In [47]:
layers = OrderedDict()
layers['conv1'] = nn.Conv2d(1, 20, 5)
layers['relu1'] = nn.ReLU()
layers['conv2'] = nn.Conv2d(20, 60, 5)
layers['relu2'] = nn.ReLU()

model = nn.Sequential(layers)
model

Sequential(
  (conv1): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
  (relu1): ReLU()
  (conv2): Conv2d(20, 60, kernel_size=(5, 5), stride=(1, 1))
  (relu2): ReLU()
)

In [48]:
# network define using functional API
# using nn.Module

import torch.nn as nn
import torch.nn.functional as F

class Model(nn.Module):
  def __init__(self):
    super(Model, self).__init__()
    self.conv1 = nn.Conv2d(1, 20, 5)
    self.conv2 = nn.Conv2d(20, 64, 5)

  def foward(self, x):
    x = F.relu(self.conv1(x))
    x = F.relu(self.conv2(x))
    return x

model = Model()  
model

Model(
  (conv1): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(20, 64, kernel_size=(5, 5), stride=(1, 1))
)

In [49]:
# network define using functional API
# using nn.Module

import torch.nn as nn
import torch.nn.functional as F

class Model(nn.Module):
  def __init__(self):
    super(Model, self).__init__()
    self.conv1 = nn.Conv2d(1, 20, 5)
    self.conv2 = nn.Conv2d(20, 64, 5)
    self.relu1 = nn.ReLU()
    self.relu2 = nn.ReLU()

  def foward(self, x):
    x = self.relu1(self.conv1(x))
    x = self.relu2(self.conv2(x))
    return x

model = Model()  
model

Model(
  (conv1): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(20, 64, kernel_size=(5, 5), stride=(1, 1))
  (relu1): ReLU()
  (relu2): ReLU()
)

In [50]:
# network define using functional API and nn.ModuleList

class Model(nn.Module):
  def __init__(self):
    super(Model, self).__init__()
    self.convs = nn.ModuleList(
        [
         nn.Conv2d(1 ,20, 5),
         nn.Conv2d(20, 64, 5)         
        ])

  def forward(self, x):
    for i, l in enumerate(self.convs):
      x = F.relu(l(x))
    return x

model = Model()
model

Model(
  (convs): ModuleList(
    (0): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
    (1): Conv2d(20, 64, kernel_size=(5, 5), stride=(1, 1))
  )
)

In [51]:
# network define using functional API and nn.ModuleList

class Model(nn.Module):
  def __init__(self):
    super(Model, self).__init__()
    self.convs = nn.ModuleList(
        [
         nn.Conv2d(1 ,20, 5),
         nn.ReLU(),
         nn.Conv2d(20, 64, 5),
         nn.ReLU()
        ])

  def forward(self, x):
    for i, l in enumerate(self.convs):
      x = l(x)
    return x

model = Model()
model

Model(
  (convs): ModuleList(
    (0): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU()
    (2): Conv2d(20, 64, kernel_size=(5, 5), stride=(1, 1))
    (3): ReLU()
  )
)

In [52]:
# network define using functional API and nn.ModuleDict

class Model(nn.Module):
  def __init__(self):
    super(Model, self).__init__()
    self.convs = nn.ModuleDict(
        {
          'conv1': nn.Conv2d(1, 20, 5),
          'relu1': nn.ReLU(),
          'conv2': nn.Conv2d(20, 64, 5),
          'relu2': nn.ReLU()
        }
    )

  def forward(self, x):
    for l in self.convs.values():
      x = l(x)
    return x

model = Model()
model

Model(
  (convs): ModuleDict(
    (conv1): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
    (conv2): Conv2d(20, 64, kernel_size=(5, 5), stride=(1, 1))
    (relu1): ReLU()
    (relu2): ReLU()
  )
)

# AutoGrad

In [53]:
# define tensor
x = torch.tensor(1, requires_grad=True, dtype=torch.float32)
w = torch.tensor(2, requires_grad=True, dtype=torch.float32)
b = torch.tensor(3, requires_grad=True, dtype=torch.float32)

# define graph

y = w * x + b

print(y)


tensor(5., grad_fn=<AddBackward0>)


In [54]:
# check gradient
print(y.backward())

None


In [55]:
print(x.grad)
print(w.grad)
print(b.grad)

tensor(2.)
tensor(1.)
tensor(1.)


In [56]:
# Freeze parameter

import torchvision

net = torchvision.models.vgg16(pretrained=True)
for param in net.features.parameters():
  param.requires_grad = False

Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to /root/.cache/torch/checkpoints/vgg16-397923af.pth
100%|██████████| 528M/528M [00:02<00:00, 239MB/s]


In [57]:
net

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace=True)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace=True)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace=True)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace=True)
    (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1

# Enable GPU

In [0]:
# Enable GPU

xf_gpu = torch.FloatTensor(1, 2).to('cuda')

In [59]:
xf_gpu

tensor([[5.0991e-36, 0.0000e+00]], device='cuda:0')

In [60]:

import torch.nn as nn
import torch.nn.functional as F

class Model(nn.Module):
  def __init__(self):
    super(Model, self).__init__()
    self.conv1 = nn.Conv2d(1, 20, 5)
    self.relu1 = nn.ReLU()
    self.conv2 = nn.Conv2d(20, 64, 5)
    self.relu2 = nn.ReLU()

  def forward(self, x):
    x = F.relu(self.conv1(x))
    x = F.relu(self.conv2(x))
    return x

net = Model()
net.to('cuda')

Model(
  (conv1): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
  (relu1): ReLU()
  (conv2): Conv2d(20, 64, kernel_size=(5, 5), stride=(1, 1))
  (relu2): ReLU()
)

# Loss Function and Optimization


In [61]:
# MSELoss
x = torch.randn(8)
y = torch.randn(8)

criterion = nn.MSELoss()
loss = criterion(x,y)
print(loss)

tensor(1.4579)


In [62]:
# CrossEntropyLoss
x = torch.randn(1, 8)
y = torch.LongTensor([1]).random_(8)

criterion = nn.CrossEntropyLoss()
loss = criterion(x, y)

print(loss)

tensor(1.9565)


In [64]:
# linear layer for optimization
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()

    # nn. Linear
    self.lin1 = nn.Linear(in_features=10, out_features=10, bias=False)

  def forward(self, x):
    x = self.lin1(x)
    return x

net = Net()
net
  

Net(
  (lin1): Linear(in_features=10, out_features=10, bias=False)
)

In [0]:
def solver(opt_conf):
  loss_list = [ ]

  # generate data
  x = torch.randn(1, 10)
  w = torch.randn(1, 1)
  y = torch.mu(w, x) + 2

  # network define
  net = Net()

  # define loss function
  criterion = nn.MSELoss()

  # Optimization method
  if opt_conf == 'sgd':
    optimizer = torch.optim.SGD(net.parameters(), lr=0.1)
  elif opt_conf == 'momentum_sgd':
    optimizer = torch.optim.SGD(net.parameters(), lr=0.1, momentum=0.9)
  elif opt_conf == 'adadelta':
    optimizer = torch.optim.Adadelta(nn.parameters(), rho=0.95, eps=1e-04)
  elif opt_conf == 'adagrad':
    optimizer = torch.optim.Adagrad(net.parameters())
  elif opt_conf == 'adam':
    optimizer = torch.optim.Adam(net.parameters(), lr=1e-1, betas=(0.9, 0.99), eps=1e-09)
  elif opt_conf == 'rmsprop':
    optimizer = torch.optim.RMSprop(net.parameters())
  else:
    print('invalid parameter')
    raise

  # train

  